# Generated by Django 3.2.19 on 2023-05-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipesingredients_unique_recipes_ingredients'),
        ('tags', '0004_alter_tags_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
