# Generated by Django 3.2.19 on 2023-05-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipesingredients_unique_recipes_ingredients'),
        ('tags', '0005_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
