# Generated by Django 3.2.19 on 2023-05-30 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipesingredients',
            name='unique_recipes_ingredients',
        ),
        migrations.AlterField(
            model_name='recipesingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Количество'),
        ),
    ]
