# Generated by Django 3.2.19 on 2023-05-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_follow',
        ),
    ]
